/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji'

export interface Config {
  auth: {
    users: UserAuthOperations
  }
  blocks: {}
  collections: {
    media: Media
    users: User
    story: Story
    capability: Capability
    solution: Solution
    industry: Industry
    scale: Scale
    model: Model
    job: Job
    team: Team
    'payload-kv': PayloadKv
    'payload-folders': FolderInterface
    'payload-locked-documents': PayloadLockedDocument
    'payload-preferences': PayloadPreference
    'payload-migrations': PayloadMigration
  }
  collectionsJoins: {
    'payload-folders': {
      documentsAndFolders: 'payload-folders' | 'media'
    }
  }
  collectionsSelect: {
    media: MediaSelect<false> | MediaSelect<true>
    users: UsersSelect<false> | UsersSelect<true>
    story: StorySelect<false> | StorySelect<true>
    capability: CapabilitySelect<false> | CapabilitySelect<true>
    solution: SolutionSelect<false> | SolutionSelect<true>
    industry: IndustrySelect<false> | IndustrySelect<true>
    scale: ScaleSelect<false> | ScaleSelect<true>
    model: ModelSelect<false> | ModelSelect<true>
    job: JobSelect<false> | JobSelect<true>
    team: TeamSelect<false> | TeamSelect<true>
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>
    'payload-folders': PayloadFoldersSelect<false> | PayloadFoldersSelect<true>
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>
  }
  db: {
    defaultIDType: string
  }
  fallbackLocale: null
  globals: {
    header: Header
    footer: Footer
    homepage: Homepage
    careersPage: CareersPage
  }
  globalsSelect: {
    header: HeaderSelect<false> | HeaderSelect<true>
    footer: FooterSelect<false> | FooterSelect<true>
    homepage: HomepageSelect<false> | HomepageSelect<true>
    careersPage: CareersPageSelect<false> | CareersPageSelect<true>
  }
  locale: null
  widgets: {
    collections: CollectionsWidget
  }
  user: User
  jobs: {
    tasks: unknown
    workflows: unknown
  }
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string
    password: string
  }
  login: {
    email: string
    password: string
  }
  registerFirstUser: {
    email: string
    password: string
  }
  unlock: {
    email: string
    password: string
  }
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: string
  alt?: string | null
  caption?: {
    root: {
      type: string
      children: {
        type: any
        version: number
        [k: string]: unknown
      }[]
      direction: ('ltr' | 'rtl') | null
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | ''
      indent: number
      version: number
    }
    [k: string]: unknown
  } | null
  prefix?: string | null
  folder?: (string | null) | FolderInterface
  updatedAt: string
  createdAt: string
  url?: string | null
  thumbnailURL?: string | null
  filename?: string | null
  mimeType?: string | null
  filesize?: number | null
  width?: number | null
  height?: number | null
  focalX?: number | null
  focalY?: number | null
  sizes?: {
    thumbnail?: {
      url?: string | null
      width?: number | null
      height?: number | null
      mimeType?: string | null
      filesize?: number | null
      filename?: string | null
    }
    square?: {
      url?: string | null
      width?: number | null
      height?: number | null
      mimeType?: string | null
      filesize?: number | null
      filename?: string | null
    }
    small?: {
      url?: string | null
      width?: number | null
      height?: number | null
      mimeType?: string | null
      filesize?: number | null
      filename?: string | null
    }
    medium?: {
      url?: string | null
      width?: number | null
      height?: number | null
      mimeType?: string | null
      filesize?: number | null
      filename?: string | null
    }
    large?: {
      url?: string | null
      width?: number | null
      height?: number | null
      mimeType?: string | null
      filesize?: number | null
      filename?: string | null
    }
    xlarge?: {
      url?: string | null
      width?: number | null
      height?: number | null
      mimeType?: string | null
      filesize?: number | null
      filename?: string | null
    }
    og?: {
      url?: string | null
      width?: number | null
      height?: number | null
      mimeType?: string | null
      filesize?: number | null
      filename?: string | null
    }
  }
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-folders".
 */
export interface FolderInterface {
  id: string
  name: string
  folder?: (string | null) | FolderInterface
  documentsAndFolders?: {
    docs?: (
      | {
          relationTo?: 'payload-folders'
          value: string | FolderInterface
        }
      | {
          relationTo?: 'media'
          value: string | Media
        }
    )[]
    hasNextPage?: boolean
    totalDocs?: number
  }
  folderType?: 'media'[] | null
  updatedAt: string
  createdAt: string
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string
  name?: string | null
  updatedAt: string
  createdAt: string
  email: string
  resetPasswordToken?: string | null
  resetPasswordExpiration?: string | null
  salt?: string | null
  hash?: string | null
  loginAttempts?: number | null
  lockUntil?: string | null
  sessions?:
    | {
        id: string
        createdAt?: string | null
        expiresAt: string
      }[]
    | null
  password?: string | null
  collection: 'users'
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "story".
 */
export interface Story {
  id: string
  title?: string | null
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null
  slug: string
  excerpts?: string | null
  thumbnail?: (string | null) | Media
  content?: {
    root: {
      type: string
      children: {
        type: any
        version: number
        [k: string]: unknown
      }[]
      direction: ('ltr' | 'rtl') | null
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | ''
      indent: number
      version: number
    }
    [k: string]: unknown
  } | null
  updatedAt: string
  createdAt: string
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "capability".
 */
export interface Capability {
  id: string
  title?: string | null
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null
  slug: string
  excerpts?: string | null
  thumbnail?: (string | null) | Media
  content?: {
    root: {
      type: string
      children: {
        type: any
        version: number
        [k: string]: unknown
      }[]
      direction: ('ltr' | 'rtl') | null
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | ''
      indent: number
      version: number
    }
    [k: string]: unknown
  } | null
  updatedAt: string
  createdAt: string
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "solution".
 */
export interface Solution {
  id: string
  title?: string | null
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null
  slug: string
  excerpts?: string | null
  thumbnail?: (string | null) | Media
  content?: {
    root: {
      type: string
      children: {
        type: any
        version: number
        [k: string]: unknown
      }[]
      direction: ('ltr' | 'rtl') | null
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | ''
      indent: number
      version: number
    }
    [k: string]: unknown
  } | null
  updatedAt: string
  createdAt: string
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "industry".
 */
export interface Industry {
  id: string
  title?: string | null
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null
  slug: string
  excerpts?: string | null
  thumbnail?: (string | null) | Media
  content?: {
    root: {
      type: string
      children: {
        type: any
        version: number
        [k: string]: unknown
      }[]
      direction: ('ltr' | 'rtl') | null
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | ''
      indent: number
      version: number
    }
    [k: string]: unknown
  } | null
  updatedAt: string
  createdAt: string
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "scale".
 */
export interface Scale {
  id: string
  title?: string | null
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null
  slug: string
  excerpts?: string | null
  thumbnail?: (string | null) | Media
  content?: {
    root: {
      type: string
      children: {
        type: any
        version: number
        [k: string]: unknown
      }[]
      direction: ('ltr' | 'rtl') | null
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | ''
      indent: number
      version: number
    }
    [k: string]: unknown
  } | null
  updatedAt: string
  createdAt: string
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "model".
 */
export interface Model {
  id: string
  title?: string | null
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null
  slug: string
  excerpts?: string | null
  thumbnail?: (string | null) | Media
  content?: {
    root: {
      type: string
      children: {
        type: any
        version: number
        [k: string]: unknown
      }[]
      direction: ('ltr' | 'rtl') | null
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | ''
      indent: number
      version: number
    }
    [k: string]: unknown
  } | null
  updatedAt: string
  createdAt: string
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "job".
 */
export interface Job {
  id: string
  code: string
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null
  slug: string
  title?: string | null
  team?: string | null
  department?: string | null
  location?: string | null
  excerpts?: string | null
  description?: {
    root: {
      type: string
      children: {
        type: any
        version: number
        [k: string]: unknown
      }[]
      direction: ('ltr' | 'rtl') | null
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | ''
      indent: number
      version: number
    }
    [k: string]: unknown
  } | null
  level?: ('Junior' | 'Mid' | 'Senior' | 'Lead' | 'C-Suite') | null
  opened: string
  closed?: string | null
  image?: (string | null) | Media
  active?: boolean | null
  updatedAt: string
  createdAt: string
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "team".
 */
export interface Team {
  id: string
  name: string
  position: string
  excerpt: string
  description: string
  image: string | Media
  linkedin?: string | null
  updatedAt: string
  createdAt: string
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: string
  key: string
  data:
    | {
        [k: string]: unknown
      }
    | unknown[]
    | string
    | number
    | boolean
    | null
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string
  document?:
    | ({
        relationTo: 'media'
        value: string | Media
      } | null)
    | ({
        relationTo: 'users'
        value: string | User
      } | null)
    | ({
        relationTo: 'story'
        value: string | Story
      } | null)
    | ({
        relationTo: 'capability'
        value: string | Capability
      } | null)
    | ({
        relationTo: 'solution'
        value: string | Solution
      } | null)
    | ({
        relationTo: 'industry'
        value: string | Industry
      } | null)
    | ({
        relationTo: 'scale'
        value: string | Scale
      } | null)
    | ({
        relationTo: 'model'
        value: string | Model
      } | null)
    | ({
        relationTo: 'job'
        value: string | Job
      } | null)
    | ({
        relationTo: 'team'
        value: string | Team
      } | null)
    | ({
        relationTo: 'payload-folders'
        value: string | FolderInterface
      } | null)
  globalSlug?: string | null
  user: {
    relationTo: 'users'
    value: string | User
  }
  updatedAt: string
  createdAt: string
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string
  user: {
    relationTo: 'users'
    value: string | User
  }
  key?: string | null
  value?:
    | {
        [k: string]: unknown
      }
    | unknown[]
    | string
    | number
    | boolean
    | null
  updatedAt: string
  createdAt: string
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string
  name?: string | null
  batch?: number | null
  updatedAt: string
  createdAt: string
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T
  caption?: T
  prefix?: T
  folder?: T
  updatedAt?: T
  createdAt?: T
  url?: T
  thumbnailURL?: T
  filename?: T
  mimeType?: T
  filesize?: T
  width?: T
  height?: T
  focalX?: T
  focalY?: T
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T
              width?: T
              height?: T
              mimeType?: T
              filesize?: T
              filename?: T
            }
        square?:
          | T
          | {
              url?: T
              width?: T
              height?: T
              mimeType?: T
              filesize?: T
              filename?: T
            }
        small?:
          | T
          | {
              url?: T
              width?: T
              height?: T
              mimeType?: T
              filesize?: T
              filename?: T
            }
        medium?:
          | T
          | {
              url?: T
              width?: T
              height?: T
              mimeType?: T
              filesize?: T
              filename?: T
            }
        large?:
          | T
          | {
              url?: T
              width?: T
              height?: T
              mimeType?: T
              filesize?: T
              filename?: T
            }
        xlarge?:
          | T
          | {
              url?: T
              width?: T
              height?: T
              mimeType?: T
              filesize?: T
              filename?: T
            }
        og?:
          | T
          | {
              url?: T
              width?: T
              height?: T
              mimeType?: T
              filesize?: T
              filename?: T
            }
      }
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T
  updatedAt?: T
  createdAt?: T
  email?: T
  resetPasswordToken?: T
  resetPasswordExpiration?: T
  salt?: T
  hash?: T
  loginAttempts?: T
  lockUntil?: T
  sessions?:
    | T
    | {
        id?: T
        createdAt?: T
        expiresAt?: T
      }
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "story_select".
 */
export interface StorySelect<T extends boolean = true> {
  title?: T
  generateSlug?: T
  slug?: T
  excerpts?: T
  thumbnail?: T
  content?: T
  updatedAt?: T
  createdAt?: T
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "capability_select".
 */
export interface CapabilitySelect<T extends boolean = true> {
  title?: T
  generateSlug?: T
  slug?: T
  excerpts?: T
  thumbnail?: T
  content?: T
  updatedAt?: T
  createdAt?: T
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "solution_select".
 */
export interface SolutionSelect<T extends boolean = true> {
  title?: T
  generateSlug?: T
  slug?: T
  excerpts?: T
  thumbnail?: T
  content?: T
  updatedAt?: T
  createdAt?: T
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "industry_select".
 */
export interface IndustrySelect<T extends boolean = true> {
  title?: T
  generateSlug?: T
  slug?: T
  excerpts?: T
  thumbnail?: T
  content?: T
  updatedAt?: T
  createdAt?: T
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "scale_select".
 */
export interface ScaleSelect<T extends boolean = true> {
  title?: T
  generateSlug?: T
  slug?: T
  excerpts?: T
  thumbnail?: T
  content?: T
  updatedAt?: T
  createdAt?: T
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "model_select".
 */
export interface ModelSelect<T extends boolean = true> {
  title?: T
  generateSlug?: T
  slug?: T
  excerpts?: T
  thumbnail?: T
  content?: T
  updatedAt?: T
  createdAt?: T
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "job_select".
 */
export interface JobSelect<T extends boolean = true> {
  code?: T
  generateSlug?: T
  slug?: T
  title?: T
  team?: T
  department?: T
  location?: T
  excerpts?: T
  description?: T
  level?: T
  opened?: T
  closed?: T
  image?: T
  active?: T
  updatedAt?: T
  createdAt?: T
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "team_select".
 */
export interface TeamSelect<T extends boolean = true> {
  name?: T
  position?: T
  excerpt?: T
  description?: T
  image?: T
  linkedin?: T
  updatedAt?: T
  createdAt?: T
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T
  data?: T
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-folders_select".
 */
export interface PayloadFoldersSelect<T extends boolean = true> {
  name?: T
  folder?: T
  documentsAndFolders?: T
  folderType?: T
  updatedAt?: T
  createdAt?: T
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T
  globalSlug?: T
  user?: T
  updatedAt?: T
  createdAt?: T
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T
  key?: T
  value?: T
  updatedAt?: T
  createdAt?: T
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T
  batch?: T
  updatedAt?: T
  createdAt?: T
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header".
 */
export interface Header {
  id: string
  logo?: (string | null) | Media
  siteName?: string | null
  menu?:
    | {
        label?: string | null
        /**
         * Optional. Leave empty if this item has sub-items.
         */
        link?: string | null
        /**
         * Add sub-items for dropdown. If empty, this is a regular link.
         */
        subItems?:
          | {
              label?: string | null
              link?: string | null
              id?: string | null
            }[]
          | null
        id?: string | null
      }[]
    | null
  button?: {
    label?: string | null
    link?: string | null
  }
  updatedAt?: string | null
  createdAt?: string | null
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer".
 */
export interface Footer {
  id: string
  menu_1?: {
    logo?: (string | null) | Media
    siteName?: string | null
    description?: string | null
    copyright?: string | null
  }
  capabilities?: (string | Capability)[] | null
  solutions?: (string | Solution)[] | null
  industries?: (string | Industry)[] | null
  menu_4?: {
    menu?:
      | {
          label?: string | null
          link?: string | null
          id?: string | null
        }[]
      | null
  }
  updatedAt?: string | null
  createdAt?: string | null
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "homepage".
 */
export interface Homepage {
  id: string
  about?: {
    heading?: string | null
    description?: string | null
    items?:
      | (
          | {
              relationTo: 'capability'
              value: string | Capability
            }
          | {
              relationTo: 'solution'
              value: string | Solution
            }
          | {
              relationTo: 'industry'
              value: string | Industry
            }
          | {
              relationTo: 'scale'
              value: string | Scale
            }
          | {
              relationTo: 'model'
              value: string | Model
            }
        )[]
      | null
    organizations?: {
      heading?: string | null
      organization?:
        | {
            icon?: (string | null) | Media
            name?: string | null
            link?: string | null
            id?: string | null
          }[]
        | null
    }
    bottomDescription?: string | null
  }
  solutions?: {
    heading?: string | null
    description?: string | null
    image?: (string | null) | Media
    items?: (string | Solution)[] | null
  }
  capabilities?: {
    heading?: string | null
    description?: string | null
    capability?: (string | Capability)[] | null
    heading_2?: string | null
    description_2?: string | null
    image?: (string | null) | Media
  }
  industries?: {
    heading?: string | null
    description?: string | null
    industry?: (string | Industry)[] | null
  }
  scales?: {
    heading?: string | null
    description?: string | null
    scale?: (string | Scale)[] | null
  }
  engagement?: {
    heading?: string | null
    description?: string | null
    model?: (string | Model)[] | null
  }
  globalDelivery?: {
    heading?: string | null
    description?: string | null
    title?: string | null
    excerpt?: string | null
    image?: (string | null) | Media
  }
  processes?: {
    heading?: string | null
    description?: string | null
    image?: (string | null) | Media
    process?:
      | {
          title?: string | null
          description?: {
            root: {
              type: string
              children: {
                type: any
                version: number
                [k: string]: unknown
              }[]
              direction: ('ltr' | 'rtl') | null
              format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | ''
              indent: number
              version: number
            }
            [k: string]: unknown
          } | null
          id?: string | null
        }[]
      | null
  }
  team?: {
    heading?: string | null
    description?: string | null
    members?:
      | {
          name?: string | null
          position?: string | null
          image?: (string | null) | Media
          linkedin?: string | null
          id?: string | null
        }[]
      | null
  }
  opportunities?: {
    heading?: string | null
    description?: string | null
    opportunity?: (string | Job)[] | null
  }
  updatedAt?: string | null
  createdAt?: string | null
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "careersPage".
 */
export interface CareersPage {
  id: string
  hero?: {
    heading?: string | null
    description?: string | null
    image?: (string | null) | Media
    button?: {
      label?: string | null
      url?: string | null
    }
  }
  section_2?: {
    heading?: string | null
    description?: string | null
    item_1?: {
      heading?: string | null
      description?: string | null
      image?: (string | null) | Media
    }
    item_2?: {
      heading?: string | null
      description?: string | null
    }
    item_3?: {
      heading?: string | null
      description?: string | null
    }
    item_4?: {
      heading?: string | null
      description?: string | null
    }
    item_5?: {
      heading?: string | null
      description?: string | null
    }
    item_6?: {
      heading?: string | null
      description?: string | null
    }
  }
  section_3?: {
    heading?: string | null
    description?: string | null
    item_1?: {
      heading?: string | null
      description?: string | null
      image?: (string | null) | Media
    }
    item_2?: {
      heading?: string | null
      description?: string | null
      image?: (string | null) | Media
    }
    item_3?: {
      heading?: string | null
      description?: string | null
    }
    item_4?: {
      heading?: string | null
      description?: string | null
    }
  }
  section_4?: {
    heading?: string | null
    description?: string | null
    item_1?: {
      heading?: string | null
      description?: string | null
      levels?:
        | {
            name?: string | null
            id?: string | null
          }[]
        | null
    }
    item_2?: {
      heading?: string | null
      description?: string | null
      image?: (string | null) | Media
    }
    item_3?: {
      heading?: string | null
      description?: string | null
      image?: (string | null) | Media
    }
    item_4?: {
      heading?: string | null
      description?: string | null
      image?: (string | null) | Media
    }
    item_5?: {
      heading?: string | null
      description?: string | null
      image?: (string | null) | Media
    }
  }
  team?: {
    heading?: string | null
    description?: string | null
    members?: (string | Team)[] | null
  }
  jobs?: {
    heading?: string | null
    description?: string | null
    list?: (string | Job)[] | null
  }
  updatedAt?: string | null
  createdAt?: string | null
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header_select".
 */
export interface HeaderSelect<T extends boolean = true> {
  logo?: T
  siteName?: T
  menu?:
    | T
    | {
        label?: T
        link?: T
        subItems?:
          | T
          | {
              label?: T
              link?: T
              id?: T
            }
        id?: T
      }
  button?:
    | T
    | {
        label?: T
        link?: T
      }
  updatedAt?: T
  createdAt?: T
  globalType?: T
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer_select".
 */
export interface FooterSelect<T extends boolean = true> {
  menu_1?:
    | T
    | {
        logo?: T
        siteName?: T
        description?: T
        copyright?: T
      }
  capabilities?: T
  solutions?: T
  industries?: T
  menu_4?:
    | T
    | {
        menu?:
          | T
          | {
              label?: T
              link?: T
              id?: T
            }
      }
  updatedAt?: T
  createdAt?: T
  globalType?: T
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "homepage_select".
 */
export interface HomepageSelect<T extends boolean = true> {
  about?:
    | T
    | {
        heading?: T
        description?: T
        items?: T
        organizations?:
          | T
          | {
              heading?: T
              organization?:
                | T
                | {
                    icon?: T
                    name?: T
                    link?: T
                    id?: T
                  }
            }
        bottomDescription?: T
      }
  solutions?:
    | T
    | {
        heading?: T
        description?: T
        image?: T
        items?: T
      }
  capabilities?:
    | T
    | {
        heading?: T
        description?: T
        capability?: T
        heading_2?: T
        description_2?: T
        image?: T
      }
  industries?:
    | T
    | {
        heading?: T
        description?: T
        industry?: T
      }
  scales?:
    | T
    | {
        heading?: T
        description?: T
        scale?: T
      }
  engagement?:
    | T
    | {
        heading?: T
        description?: T
        model?: T
      }
  globalDelivery?:
    | T
    | {
        heading?: T
        description?: T
        title?: T
        excerpt?: T
        image?: T
      }
  processes?:
    | T
    | {
        heading?: T
        description?: T
        image?: T
        process?:
          | T
          | {
              title?: T
              description?: T
              id?: T
            }
      }
  team?:
    | T
    | {
        heading?: T
        description?: T
        members?:
          | T
          | {
              name?: T
              position?: T
              image?: T
              linkedin?: T
              id?: T
            }
      }
  opportunities?:
    | T
    | {
        heading?: T
        description?: T
        opportunity?: T
      }
  updatedAt?: T
  createdAt?: T
  globalType?: T
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "careersPage_select".
 */
export interface CareersPageSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        heading?: T
        description?: T
        image?: T
        button?:
          | T
          | {
              label?: T
              url?: T
            }
      }
  section_2?:
    | T
    | {
        heading?: T
        description?: T
        item_1?:
          | T
          | {
              heading?: T
              description?: T
              image?: T
            }
        item_2?:
          | T
          | {
              heading?: T
              description?: T
            }
        item_3?:
          | T
          | {
              heading?: T
              description?: T
            }
        item_4?:
          | T
          | {
              heading?: T
              description?: T
            }
        item_5?:
          | T
          | {
              heading?: T
              description?: T
            }
        item_6?:
          | T
          | {
              heading?: T
              description?: T
            }
      }
  section_3?:
    | T
    | {
        heading?: T
        description?: T
        item_1?:
          | T
          | {
              heading?: T
              description?: T
              image?: T
            }
        item_2?:
          | T
          | {
              heading?: T
              description?: T
              image?: T
            }
        item_3?:
          | T
          | {
              heading?: T
              description?: T
            }
        item_4?:
          | T
          | {
              heading?: T
              description?: T
            }
      }
  section_4?:
    | T
    | {
        heading?: T
        description?: T
        item_1?:
          | T
          | {
              heading?: T
              description?: T
              levels?:
                | T
                | {
                    name?: T
                    id?: T
                  }
            }
        item_2?:
          | T
          | {
              heading?: T
              description?: T
              image?: T
            }
        item_3?:
          | T
          | {
              heading?: T
              description?: T
              image?: T
            }
        item_4?:
          | T
          | {
              heading?: T
              description?: T
              image?: T
            }
        item_5?:
          | T
          | {
              heading?: T
              description?: T
              image?: T
            }
      }
  team?:
    | T
    | {
        heading?: T
        description?: T
        members?: T
      }
  jobs?:
    | T
    | {
        heading?: T
        description?: T
        list?: T
      }
  updatedAt?: T
  createdAt?: T
  globalType?: T
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown
  }
  width: 'full'
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown
}

declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}
