import type { NavIcon } from '@/globals/nav/iconOptions'
import {
  ArrowUpRight,
  BookMarked,
  BookOpen,
  Boxes,
  Brain,
  Briefcase,
  Building2,
  Cloud,
  Code2,
  Compass,
  Cpu,
  Database,
  Factory,
  Globe,
  HeartPulse,
  Landmark,
  Layers,
  LineChart,
  type LucideIcon,
  Mail,
  Network,
  Newspaper,
  Phone,
  Plane,
  Rocket,
  Search,
  Server,
  ShieldCheck,
  ShoppingBag,
  Smartphone,
  Sparkles,
  Trophy,
  Users,
  Workflow,
  Zap,
} from 'lucide-react'

// Maps every CMS icon value (see src/globals/nav/iconOptions.ts) to a lucide component. A value with
// no entry here renders nothing — keep this in sync with NAV_ICONS.
const MEGA_ICONS: Record<NavIcon, LucideIcon> = {
  'arrow-up-right': ArrowUpRight,
  sparkles: Sparkles,
  brain: Brain,
  database: Database,
  cloud: Cloud,
  layers: Layers,
  cpu: Cpu,
  code: Code2,
  smartphone: Smartphone,
  globe: Globe,
  users: Users,
  'book-open': BookOpen,
  'book-marked': BookMarked,
  rocket: Rocket,
  building: Building2,
  'shield-check': ShieldCheck,
  'line-chart': LineChart,
  boxes: Boxes,
  network: Network,
  server: Server,
  zap: Zap,
  briefcase: Briefcase,
  newspaper: Newspaper,
  search: Search,
  factory: Factory,
  'heart-pulse': HeartPulse,
  landmark: Landmark,
  'shopping-bag': ShoppingBag,
  plane: Plane,
  trophy: Trophy,
  workflow: Workflow,
  compass: Compass,
  phone: Phone,
  mail: Mail,
}

/** Renders the lucide glyph for a CMS icon value, or `null` when the value is empty/unknown. */
export function NavIcon({ name, className }: { name?: string | null; className?: string }) {
  const Icon = name ? MEGA_ICONS[name as NavIcon] : undefined
  if (!Icon) return null
  return <Icon className={className} aria-hidden strokeWidth={1.75} />
}
